CREATE TABLE tipo_cliente (
id int PRIMARY KEY,
descricao varchar(50)
);

CREATE TABLE cliente (
id int PRIMARY KEY,
nome varchar(50),
idade int,
tp_cliente int REFERENCES tipo_cliente (id),
endereco varchar(150)
);

CREATE TABLE dependente (
id int PRIMARY KEY, 
nome varchar(50),
idade int,
id_cliente int REFERENCES cliente (id)
);

insert into tipo_cliente values (1, 'NOVO');
insert into tipo_cliente values (2, 'FIDELIZADO');
insert into tipo_cliente values (3, 'PROBLEMATICO');


INSERT INTO CLIENTE VALUES (1, 'JOAO', 30, 1, 'RUA ABC');

INSERT INTO CLIENTE VALUES (2, 'PAULO', 32, 2, 'RUA 123');
INSERT INTO CLIENTE VALUES (3, 'JOSE', 40, 2, 'RUA HJY');
INSERT INTO CLIENTE VALUES (4, 'MARIA', 27, 1, 'RUA AAA');
INSERT INTO CLIENTE VALUES (5, 'CLAUDIA', 28, 1, 'RUA KKK');
INSERT INTO CLIENTE VALUES (6, 'MARIANA', 22, 2, 'RUA LLL');
INSERT INTO CLIENTE VALUES (7, 'JULIANA', 30, 2, 'RUA OOO');

INSERT INTO DEPENDENTE VALUES (1, 'JOAOZINHO', 12, 1);
INSERT INTO DEPENDENTE VALUES (2, 'MARIAZINHA', 10, 1);

INSERT INTO DEPENDENTE VALUES (3, 'PAULINHO', 12, 2);
INSERT INTO DEPENDENTE VALUES (4, 'JOAQUINA', 10, 2);
INSERT INTO DEPENDENTE VALUES (5, 'FERNANDA', 10, 2);

INSERT INTO DEPENDENTE VALUES (6, 'PAULINHO', 12, 3);

INSERT INTO DEPENDENTE VALUES (7, 'ZEZINHO', 8, 4);
INSERT INTO DEPENDENTE VALUES (8, 'HEPAMINONDAS', 38, 4);
